package com.jobpilot.observability;

public enum OperationalCounter {
    TELEGRAM_UPDATES_PROCESSED,
    TELEGRAM_UPDATES_RETRIED,
    TELEGRAM_UPDATES_DEAD_LETTERED,
    ANALYSES_CREATED,
    ANALYSES_CACHED,
    ANALYSES_FALLBACK,
    ANALYSES_BUDGET_REJECTED,
    ANALYSES_FAILED,
    DOCUMENTS_CREATED,
    DOCUMENTS_CACHED,
    DOCUMENTS_FALLBACK,
    DOCUMENTS_FAILED,
    MAINTENANCE_ITEMS_RECOVERED,
    MAINTENANCE_ITEMS_REMOVED
}
