package com.jobpilot.llm.domain;

public enum LlmFailureCategory {
    DISABLED,
    CONFIGURATION,
    AUTHENTICATION,
    CONNECTION,
    TIMEOUT,
    RATE_LIMITED,
    PROVIDER_ERROR,
    RESPONSE_TOO_LARGE,
    MALFORMED_RESPONSE,
    SCHEMA_VALIDATION,
    TRUTHFULNESS_VALIDATION,
    CONCURRENT_REQUEST,
    DATABASE_ERROR,
    CALL_LIMIT,
    BUDGET_EXHAUSTED,
    UNKNOWN
}
