-- Phase 3.1: per-tenant ATS source health and failure classification.
-- Additive only: no existing row is modified or removed.

-- Correlates the existing per-provider aggregate log with one ingestion run.
-- Nullable so every legacy row stays valid.
ALTER TABLE source_fetch_logs ADD COLUMN ingestion_run_id UUID;

CREATE INDEX source_fetch_logs_run_idx ON source_fetch_logs(ingestion_run_id);

-- Immutable history: exactly one row per tenant fetch attempt.
CREATE TABLE source_tenant_fetch_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingestion_run_id UUID NOT NULL,
    provider VARCHAR(50) NOT NULL,
    tenant VARCHAR(100) NOT NULL,
    attempt_status VARCHAR(20) NOT NULL,
    failure_category VARCHAR(30) NOT NULL DEFAULT 'NONE',
    http_status INTEGER,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    error_type VARCHAR(120),
    error_message VARCHAR(500),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT source_tenant_fetch_logs_status_ck CHECK (
        attempt_status IN ('SUCCESS', 'EMPTY_SUCCESS', 'FAILURE')),
    CONSTRAINT source_tenant_fetch_logs_category_ck CHECK (
        failure_category IN ('NONE', 'INVALID_TENANT', 'CLIENT_ERROR', 'AUTHORIZATION_ERROR',
            'RATE_LIMITED', 'TIMEOUT', 'NETWORK_ERROR', 'SERVER_ERROR', 'RESPONSE_PARSE_ERROR',
            'CONFIGURATION_ERROR', 'UNKNOWN_ERROR')),
    CONSTRAINT source_tenant_fetch_logs_counts_ck CHECK (fetched_count >= 0 AND duration_ms >= 0),
    CONSTRAINT source_tenant_fetch_logs_http_status_ck CHECK (
        http_status IS NULL OR (http_status >= 100 AND http_status <= 599))
);

CREATE INDEX source_tenant_fetch_logs_provider_tenant_idx
    ON source_tenant_fetch_logs(provider, tenant, started_at DESC);
CREATE INDEX source_tenant_fetch_logs_run_idx ON source_tenant_fetch_logs(ingestion_run_id);
CREATE INDEX source_tenant_fetch_logs_started_idx ON source_tenant_fetch_logs(started_at DESC);
CREATE INDEX source_tenant_fetch_logs_category_idx ON source_tenant_fetch_logs(failure_category);

-- Current roll-up: exactly one row per provider + tenant.
CREATE TABLE source_tenant_health (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    tenant VARCHAR(100) NOT NULL,
    last_attempt_status VARCHAR(20) NOT NULL,
    last_failure_category VARCHAR(30) NOT NULL DEFAULT 'NONE',
    last_http_status INTEGER,
    last_fetched_count INTEGER NOT NULL DEFAULT 0,
    last_duration_ms BIGINT NOT NULL DEFAULT 0,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    total_attempts BIGINT NOT NULL DEFAULT 0,
    total_successes BIGINT NOT NULL DEFAULT 0,
    total_failures BIGINT NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_failure_at TIMESTAMP WITH TIME ZONE,
    last_error_type VARCHAR(120),
    last_error_message VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT source_tenant_health_uk UNIQUE (provider, tenant),
    CONSTRAINT source_tenant_health_status_ck CHECK (
        last_attempt_status IN ('SUCCESS', 'EMPTY_SUCCESS', 'FAILURE')),
    CONSTRAINT source_tenant_health_category_ck CHECK (
        last_failure_category IN ('NONE', 'INVALID_TENANT', 'CLIENT_ERROR', 'AUTHORIZATION_ERROR',
            'RATE_LIMITED', 'TIMEOUT', 'NETWORK_ERROR', 'SERVER_ERROR', 'RESPONSE_PARSE_ERROR',
            'CONFIGURATION_ERROR', 'UNKNOWN_ERROR')),
    CONSTRAINT source_tenant_health_counts_ck CHECK (
        last_fetched_count >= 0 AND last_duration_ms >= 0 AND consecutive_failures >= 0
        AND total_attempts >= 0 AND total_successes >= 0 AND total_failures >= 0
        AND total_attempts = total_successes + total_failures),
    CONSTRAINT source_tenant_health_http_status_ck CHECK (
        last_http_status IS NULL OR (last_http_status >= 100 AND last_http_status <= 599))
);

CREATE INDEX source_tenant_health_provider_tenant_idx ON source_tenant_health(provider, tenant);
CREATE INDEX source_tenant_health_last_attempt_idx ON source_tenant_health(last_attempt_at DESC);
CREATE INDEX source_tenant_health_last_success_idx ON source_tenant_health(last_success_at DESC);
CREATE INDEX source_tenant_health_consecutive_failures_idx
    ON source_tenant_health(consecutive_failures DESC);
CREATE INDEX source_tenant_health_category_idx ON source_tenant_health(last_failure_category);
