-- Telegram-first job review workflow.
-- UNREVIEWED is represented by the absence of a job_workflow_state row, so no triage
-- state is written for vacancies that already exist when this migration is applied.
CREATE TABLE job_workflow_state (
    job_id BIGINT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    note VARCHAR(1000),
    applied_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT job_workflow_state_status_ck CHECK (
        status IN ('SAVED', 'APPLIED', 'DISMISSED')
    ),
    CONSTRAINT job_workflow_state_note_ck CHECK (
        note IS NULL OR (TRIM(note) <> '' AND CHAR_LENGTH(note) <= 1000)
    ),
    CONSTRAINT job_workflow_state_applied_at_ck CHECK (
        (status = 'APPLIED' AND applied_at IS NOT NULL)
        OR (status <> 'APPLIED' AND applied_at IS NULL)
    ),
    CONSTRAINT job_workflow_state_timestamps_ck CHECK (
        updated_at >= created_at
    )
);

-- Queues order by UNREVIEWED, then SAVED, then score, then recency, then job id.
CREATE INDEX job_workflow_state_status_idx
    ON job_workflow_state(status, updated_at DESC, job_id DESC);
CREATE INDEX job_workflow_state_applied_idx
    ON job_workflow_state(applied_at DESC, job_id DESC);

-- One row per confirmed Telegram send. Rows are written only after the Bot API
-- reports success, so a failed send stays retryable on the next ingestion run.
CREATE TABLE telegram_job_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    delivery_type VARCHAR(24) NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT telegram_job_delivery_type_ck CHECK (
        delivery_type IN ('MATCH_NOTIFICATION', 'REVIEW_DIGEST_ITEM')
    ),
    CONSTRAINT telegram_job_delivery_uk UNIQUE (chat_id, job_id, delivery_type)
);

CREATE INDEX telegram_job_delivery_job_idx
    ON telegram_job_delivery(job_id, delivery_type);
CREATE INDEX telegram_job_delivery_chat_idx
    ON telegram_job_delivery(chat_id, delivery_type, delivered_at DESC);
