-- Mini App P0-B: deterministic ordering, idempotency and server-owned Undo.
--
-- Two additive tables. Nothing existing is altered, so rolling back is dropping these two
-- tables: the Mini App then loses ordering/undo and behaves exactly as it did in P0-A.
--
-- See docs/mini-app-p0b-consistency-model.md. Two things this schema deliberately is NOT:
--
--   * mutation_revision is NOT a version of all data the snapshot shows. Telegram commands,
--     ApplicationController and ingestion all change snapshot data without touching it. It
--     orders MINI APP MUTATIONS ONLY; stale reads are suppressed by client read epochs.
--   * created_application / created_history_id are provenance, not freshness. They say what
--     this mutation made. Whether it is still the state being reversed is a separate check
--     against resulting_* below.

-- One row. Locked FOR UPDATE as the first statement of every Mini App mutation, so
-- mutation_revision order is commit order: the lock is held until commit, which a sequence
-- cannot promise. Intentional single-user tradeoff — Mini App mutations serialize on this
-- row. Multi-user would move this to per-user revision ownership; not implemented here.
CREATE TABLE mini_app_state (
    id SMALLINT PRIMARY KEY,
    mutation_revision BIGINT NOT NULL,
    CONSTRAINT mini_app_state_singleton_ck CHECK (id = 1),
    CONSTRAINT mini_app_state_revision_ck CHECK (mutation_revision >= 0)
);

INSERT INTO mini_app_state (id, mutation_revision) VALUES (1, 0);

-- One row per accepted Mini App mutation: the idempotency key, the revision it produced,
-- the durable state immediately before it (so Undo is a server operation, not a client
-- guess), and a fingerprint of the state it produced (so a stale Undo is provable).
CREATE TABLE mini_app_mutation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Client-generated. UNIQUE is the idempotency mechanism: duplicate delivery is resolved
    -- by the database, never by application logic.
    mutation_key VARCHAR(64) NOT NULL UNIQUE,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,

    kind VARCHAR(20) NOT NULL,
    requested_status VARCHAR(20) NOT NULL,

    -- Strictly increasing, assigned under the mini_app_state row lock. Mini App mutations
    -- only; see the header note on what this does not order.
    mutation_revision BIGINT NOT NULL UNIQUE,
    changed BOOLEAN NOT NULL,

    -- ---- state immediately BEFORE this mutation, for restoration -------------------
    -- NULL previous_workflow_status means UNREVIEWED, i.e. no job_workflow_state row.
    previous_workflow_status VARCHAR(20),
    previous_workflow_note VARCHAR(1000),
    previous_workflow_applied_at TIMESTAMP WITH TIME ZONE,
    -- NULL means no application row existed for this job.
    previous_application_status VARCHAR(40),
    -- Restored verbatim rather than recomputed: a SAVED -> APPLIED mutation stamps
    -- applications.application_date, and reversing it must put back exactly what was there,
    -- not what a rule guesses should have been there.
    previous_application_applied_at TIMESTAMP WITH TIME ZONE,
    -- True only when this mutation itself inserted the application row. The sole basis on
    -- which a reversal may delete it; current status is never sufficient.
    created_application BOOLEAN NOT NULL,
    -- The single history row this mutation appended, if any. A reversal may remove that row
    -- and no other.
    created_history_id BIGINT REFERENCES application_status_history(id) ON DELETE SET NULL,

    -- ---- fingerprint of the state this mutation PRODUCED, for freshness ------------
    -- A reversal is valid only while the durable state still matches all three. Any later
    -- writer -- a newer Mini App mutation, a Telegram command, ApplicationController --
    -- moves at least one of them, which makes the old undo token deterministically stale.
    -- Deliberately not timestamps.
    resulting_workflow_status VARCHAR(20),
    resulting_application_version BIGINT,
    resulting_history_id BIGINT,
    -- What the operation result reports when a duplicate request replays this mutation, so a
    -- replay reconstructs the recorded outcome instead of re-deriving it from current state.
    resulting_application_status VARCHAR(40),

    reversal_state VARCHAR(20) NOT NULL,
    reversed_by_mutation_id BIGINT REFERENCES mini_app_mutation(id) ON DELETE SET NULL,
    -- Opaque to the client, and immutable once issued. Liveness is reversal_state, NOT the
    -- presence of this column: retaining a spent token is what lets a replayed undo prove it is
    -- the same operation rather than a new one aimed at a different mutation.
    undo_token VARCHAR(64) UNIQUE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT mini_app_mutation_kind_ck CHECK (
        kind IN ('WORKFLOW', 'REVERSAL')
    ),
    CONSTRAINT mini_app_mutation_requested_status_ck CHECK (
        requested_status IN ('SAVED', 'APPLIED', 'DISMISSED', 'UNREVIEWED')
    ),
    CONSTRAINT mini_app_mutation_previous_workflow_status_ck CHECK (
        previous_workflow_status IS NULL
            OR previous_workflow_status IN ('SAVED', 'APPLIED', 'DISMISSED')
    ),
    CONSTRAINT mini_app_mutation_resulting_workflow_status_ck CHECK (
        resulting_workflow_status IS NULL
            OR resulting_workflow_status IN ('SAVED', 'APPLIED', 'DISMISSED')
    ),
    CONSTRAINT mini_app_mutation_previous_application_status_ck CHECK (
        previous_application_status IS NULL OR previous_application_status IN
            ('SAVED', 'APPLIED', 'INTERVIEW', 'REJECTED', 'OFFER', 'WITHDRAWN')
    ),
    CONSTRAINT mini_app_mutation_resulting_application_status_ck CHECK (
        resulting_application_status IS NULL OR resulting_application_status IN
            ('SAVED', 'APPLIED', 'INTERVIEW', 'REJECTED', 'OFFER', 'WITHDRAWN')
    ),
    CONSTRAINT mini_app_mutation_application_version_ck CHECK (
        resulting_application_version IS NULL OR resulting_application_version >= 0
    ),
    CONSTRAINT mini_app_mutation_reversal_state_ck CHECK (
        reversal_state IN ('REVERSIBLE', 'REVERSED', 'SUPERSEDED', 'NOT_REVERSIBLE')
    ),
    -- A mutation that changed nothing is never reversible and is issued no token; everything
    -- that was once reversible keeps its token forever. A spent token is not a live one --
    -- only reversal_state = 'REVERSIBLE' says that -- so replay can recognise it without
    -- being able to act on it.
    CONSTRAINT mini_app_mutation_undo_token_ck CHECK (
        (reversal_state = 'NOT_REVERSIBLE' AND undo_token IS NULL)
        OR (reversal_state <> 'NOT_REVERSIBLE' AND undo_token IS NOT NULL)
    ),
    CONSTRAINT mini_app_mutation_reversed_by_ck CHECK (
        (reversal_state = 'REVERSED' AND reversed_by_mutation_id IS NOT NULL)
        OR (reversal_state <> 'REVERSED' AND reversed_by_mutation_id IS NULL)
    )
);

-- "What is the newest Mini App mutation for this job?" runs on every reversal.
CREATE INDEX mini_app_mutation_job_idx ON mini_app_mutation(job_id, mutation_revision DESC);
