-- Multi-user foundation, step 1: candidate_profiles gains an explicit owner.
--
-- This migration establishes ownership ONLY. profile_version and active_slot are still
-- globally UNIQUE exactly as V2 declared them, so the schema continues to admit one active
-- profile and one profile per version for the whole installation rather than per candidate.
-- Those two constraints are the remaining single-candidate assumption and are rewritten in a
-- dedicated follow-up; nothing added here depends on them.

CREATE TABLE candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stable_key VARCHAR(100) NOT NULL UNIQUE CHECK (TRIM(stable_key) <> ''),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- The owner of every profile that exists today. 'default' is the value committed as
-- jobpilot.candidate-profile.candidate-key. Bootstrap resolves this row by its stable key and
-- never by id, so the seeded identity holds whatever id the sequence hands out here.
INSERT INTO candidates (stable_key, created_at, updated_at)
VALUES ('default', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE candidate_profiles ADD COLUMN candidate_id BIGINT;

-- Backfills every stored profile version, active and superseded alike: history belongs to the
-- same candidate as the current version. On a fresh database this updates zero rows, because
-- bootstrap only runs once the application starts, and the NOT NULL below still holds.
UPDATE candidate_profiles
SET candidate_id = (SELECT id FROM candidates WHERE stable_key = 'default')
WHERE candidate_id IS NULL;

ALTER TABLE candidate_profiles ALTER COLUMN candidate_id SET NOT NULL;

-- RESTRICT, not CASCADE: profile versions are referenced by resume_versions under the same
-- rule, and no code path deletes a candidate.
ALTER TABLE candidate_profiles ADD CONSTRAINT candidate_profiles_candidate_fk
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE RESTRICT;

-- Every candidate-scoped profile lookup filters on this column.
CREATE INDEX candidate_profiles_candidate_idx ON candidate_profiles(candidate_id);
