CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(100) NOT NULL,
    external_id VARCHAR(255),
    canonical_url VARCHAR(2000) NOT NULL,
    title VARCHAR(500) NOT NULL,
    company VARCHAR(300) NOT NULL,
    location VARCHAR(300),
    remote_type VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    employment_type VARCHAR(80),
    description TEXT NOT NULL,
    responsibilities TEXT,
    required_skills TEXT,
    preferred_skills TEXT,
    required_experience_years NUMERIC(4,1),
    education_requirement TEXT,
    student_year_requirement TEXT,
    language_requirements TEXT,
    salary_text VARCHAR(500),
    published_at TIMESTAMPTZ,
    deadline TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(40) NOT NULL,
    raw_payload_hash VARCHAR(64) NOT NULL,
    description_hash VARCHAR(64) NOT NULL,
    normalized_fingerprint VARCHAR(64) NOT NULL,
    CONSTRAINT jobs_canonical_url_uk UNIQUE (canonical_url)
);
CREATE UNIQUE INDEX jobs_source_external_uk ON jobs(source, external_id) WHERE external_id IS NOT NULL;
CREATE INDEX jobs_company_title_idx ON jobs(lower(company), lower(title));
CREATE INDEX jobs_published_idx ON jobs(published_at DESC);
CREATE INDEX jobs_status_idx ON jobs(status);
CREATE INDEX jobs_fingerprint_idx ON jobs(normalized_fingerprint);
CREATE INDEX jobs_description_hash_idx ON jobs(description_hash);

CREATE TABLE job_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,
    seniority VARCHAR(80),
    internship_or_trainee BOOLEAN NOT NULL DEFAULT false,
    required_experience_years NUMERIC(4,1),
    required_education TEXT,
    final_year_mandatory BOOLEAN NOT NULL DEFAULT false,
    technologies TEXT,
    programming_languages TEXT,
    spoken_languages TEXT,
    extracted_location VARCHAR(300),
    remote_eligibility VARCHAR(300),
    mentorship_signals TEXT,
    work_authorization TEXT,
    salary TEXT,
    application_deadline TIMESTAMPTZ,
    extraction_method VARCHAR(30) NOT NULL,
    raw_json TEXT
);

CREATE TABLE job_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,
    score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 100),
    band VARCHAR(40) NOT NULL,
    suitable BOOLEAN NOT NULL,
    formal_eligibility INTEGER NOT NULL,
    java_backend INTEGER NOT NULL,
    trainee_quality INTEGER NOT NULL,
    supporting_technology INTEGER NOT NULL,
    location_format INTEGER NOT NULL,
    experience_compatibility INTEGER NOT NULL,
    freshness INTEGER NOT NULL,
    penalties INTEGER NOT NULL,
    strengths TEXT NOT NULL,
    risks TEXT NOT NULL,
    hard_blockers TEXT NOT NULL,
    scored_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX job_scores_score_idx ON job_scores(score DESC);

CREATE TABLE source_fetch_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(100) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    saved_count INTEGER NOT NULL DEFAULT 0,
    error_summary VARCHAR(500)
);
CREATE INDEX source_fetch_logs_source_time_idx ON source_fetch_logs(source_name, started_at DESC);
