CREATE TABLE candidate_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_version INTEGER NOT NULL UNIQUE CHECK (profile_version > 0),
    full_name VARCHAR(200) NOT NULL CHECK (TRIM(full_name) <> ''),
    location VARCHAR(300) NOT NULL CHECK (TRIM(location) <> ''),
    education_institution VARCHAR(300) NOT NULL CHECK (TRIM(education_institution) <> ''),
    degree VARCHAR(300) NOT NULL CHECK (TRIM(degree) <> ''),
    study_start_year INTEGER NOT NULL CHECK (study_start_year BETWEEN 1950 AND 2100),
    study_end_year INTEGER CHECK (study_end_year BETWEEN study_start_year AND 2100),
    current_student BOOLEAN NOT NULL,
    final_year_student BOOLEAN NOT NULL,
    commercial_java_experience_years NUMERIC(5,2) NOT NULL
        CHECK (commercial_java_experience_years BETWEEN 0 AND 80),
    source_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL,
    active_slot SMALLINT UNIQUE,
    CONSTRAINT candidate_profiles_active_slot_ck CHECK (
        (active = TRUE AND active_slot = 1)
        OR (active = FALSE AND active_slot IS NULL)
    )
);

CREATE TABLE candidate_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(id) ON DELETE CASCADE,
    stable_key VARCHAR(100) NOT NULL CHECK (TRIM(stable_key) <> ''),
    normalized_name VARCHAR(200) NOT NULL CHECK (TRIM(normalized_name) <> ''),
    display_name VARCHAR(200) NOT NULL CHECK (TRIM(display_name) <> ''),
    category VARCHAR(60) NOT NULL,
    evidence_text TEXT NOT NULL CHECK (TRIM(evidence_text) <> ''),
    active BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT candidate_skills_stable_key_uk UNIQUE (candidate_profile_id, stable_key),
    CONSTRAINT candidate_skills_normalized_name_uk UNIQUE (candidate_profile_id, normalized_name)
);
CREATE INDEX candidate_skills_profile_idx ON candidate_skills(candidate_profile_id, display_order);

CREATE TABLE candidate_languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(id) ON DELETE CASCADE,
    stable_key VARCHAR(100) NOT NULL CHECK (TRIM(stable_key) <> ''),
    language VARCHAR(100) NOT NULL CHECK (TRIM(language) <> ''),
    verified_level VARCHAR(60) NOT NULL,
    allowed_in_cv BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT candidate_languages_stable_key_uk UNIQUE (candidate_profile_id, stable_key),
    CONSTRAINT candidate_languages_language_uk UNIQUE (candidate_profile_id, language)
);
CREATE INDEX candidate_languages_profile_idx ON candidate_languages(candidate_profile_id, display_order);

CREATE TABLE candidate_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(id) ON DELETE CASCADE,
    stable_key VARCHAR(100) NOT NULL CHECK (TRIM(stable_key) <> ''),
    name VARCHAR(300) NOT NULL CHECK (TRIM(name) <> ''),
    description TEXT NOT NULL CHECK (TRIM(description) <> ''),
    project_type VARCHAR(60) NOT NULL,
    technologies TEXT NOT NULL CHECK (TRIM(technologies) <> ''),
    active BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT candidate_projects_stable_key_uk UNIQUE (candidate_profile_id, stable_key),
    CONSTRAINT candidate_projects_name_uk UNIQUE (candidate_profile_id, name)
);
CREATE INDEX candidate_projects_profile_idx ON candidate_projects(candidate_profile_id, display_order);

CREATE TABLE candidate_project_bullets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES candidate_projects(id) ON DELETE CASCADE,
    stable_key VARCHAR(100) NOT NULL CHECK (TRIM(stable_key) <> ''),
    verified_text TEXT NOT NULL CHECK (TRIM(verified_text) <> ''),
    keywords TEXT NOT NULL,
    active BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT candidate_project_bullets_stable_key_uk UNIQUE (project_id, stable_key)
);
CREATE INDEX candidate_project_bullets_project_idx
    ON candidate_project_bullets(project_id, display_order);

CREATE TABLE resume_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(id) ON DELETE RESTRICT,
    profile_version INTEGER NOT NULL CHECK (profile_version > 0),
    selected_title VARCHAR(200) NOT NULL CHECK (TRIM(selected_title) <> ''),
    summary TEXT NOT NULL CHECK (TRIM(summary) <> ''),
    plain_text_preview TEXT NOT NULL CHECK (TRIM(plain_text_preview) <> ''),
    change_summary TEXT NOT NULL,
    interview_claims TEXT NOT NULL,
    docx_path VARCHAR(1000),
    pdf_path VARCHAR(1000),
    content_hash VARCHAR(64) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX resume_versions_job_idx ON resume_versions(job_id, generated_at DESC);
CREATE INDEX resume_versions_profile_idx ON resume_versions(candidate_profile_id);
CREATE INDEX resume_versions_content_hash_idx ON resume_versions(content_hash);

CREATE TABLE resume_version_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_version_id BIGINT NOT NULL REFERENCES resume_versions(id) ON DELETE CASCADE,
    candidate_skill_id BIGINT NOT NULL REFERENCES candidate_skills(id) ON DELETE RESTRICT,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT resume_version_skills_fact_uk UNIQUE (resume_version_id, candidate_skill_id),
    CONSTRAINT resume_version_skills_order_uk UNIQUE (resume_version_id, display_order)
);

CREATE TABLE resume_version_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_version_id BIGINT NOT NULL REFERENCES resume_versions(id) ON DELETE CASCADE,
    candidate_project_id BIGINT NOT NULL REFERENCES candidate_projects(id) ON DELETE RESTRICT,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT resume_version_projects_fact_uk UNIQUE (resume_version_id, candidate_project_id),
    CONSTRAINT resume_version_projects_order_uk UNIQUE (resume_version_id, display_order)
);

CREATE TABLE resume_version_project_bullets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_version_id BIGINT NOT NULL REFERENCES resume_versions(id) ON DELETE CASCADE,
    candidate_project_bullet_id BIGINT NOT NULL
        REFERENCES candidate_project_bullets(id) ON DELETE RESTRICT,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    CONSTRAINT resume_version_project_bullets_fact_uk
        UNIQUE (resume_version_id, candidate_project_bullet_id),
    CONSTRAINT resume_version_project_bullets_order_uk
        UNIQUE (resume_version_id, display_order)
);

CREATE TABLE cover_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(id) ON DELETE RESTRICT,
    resume_version_id BIGINT REFERENCES resume_versions(id) ON DELETE SET NULL,
    content TEXT NOT NULL CHECK (TRIM(content) <> ''),
    content_hash VARCHAR(64) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX cover_notes_job_idx ON cover_notes(job_id, generated_at DESC);
CREATE INDEX cover_notes_profile_idx ON cover_notes(candidate_profile_id);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE RESTRICT,
    status VARCHAR(40) NOT NULL CHECK (
        status IN ('SAVED', 'APPLIED', 'INTERVIEW', 'REJECTED', 'OFFER', 'WITHDRAWN')
    ),
    application_date TIMESTAMP WITH TIME ZONE,
    resume_version_id BIGINT REFERENCES resume_versions(id) ON DELETE SET NULL,
    cover_note_id BIGINT REFERENCES cover_notes(id) ON DELETE SET NULL,
    notes TEXT,
    next_follow_up_date DATE,
    interview_date TIMESTAMP WITH TIME ZONE,
    rejection_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX applications_status_idx ON applications(status, updated_at DESC);

CREATE TABLE llm_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES jobs(id) ON DELETE SET NULL,
    operation_type VARCHAR(60) NOT NULL,
    provider VARCHAR(120) NOT NULL CHECK (TRIM(provider) <> ''),
    model VARCHAR(200) NOT NULL CHECK (TRIM(model) <> ''),
    input_tokens BIGINT CHECK (input_tokens IS NULL OR input_tokens >= 0),
    output_tokens BIGINT CHECK (output_tokens IS NULL OR output_tokens >= 0),
    token_count_estimated BOOLEAN NOT NULL,
    estimated_cost_usd NUMERIC(12,6) NOT NULL CHECK (estimated_cost_usd >= 0),
    status VARCHAR(40) NOT NULL,
    fallback_used BOOLEAN NOT NULL,
    failure_category VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX llm_usage_events_created_idx ON llm_usage_events(created_at);
CREATE INDEX llm_usage_events_job_idx ON llm_usage_events(job_id);

CREATE TABLE telegram_bot_state (
    state_key VARCHAR(80) PRIMARY KEY,
    last_processed_update_id BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT telegram_bot_state_singleton_ck CHECK (state_key = 'long-polling')
);
