ALTER TABLE applications
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE applications ADD CONSTRAINT applications_notes_length_ck
    CHECK (notes IS NULL OR (TRIM(notes) <> '' AND CHAR_LENGTH(notes) <= 2000));
ALTER TABLE applications ADD CONSTRAINT applications_rejection_reason_length_ck
    CHECK (rejection_reason IS NULL
        OR (TRIM(rejection_reason) <> '' AND CHAR_LENGTH(rejection_reason) <= 1000));

ALTER TABLE telegram_bot_state
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE telegram_bot_state ADD COLUMN failed_update_id BIGINT;
ALTER TABLE telegram_bot_state ADD COLUMN failed_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE telegram_bot_state ADD CONSTRAINT telegram_bot_state_failed_attempts_ck
    CHECK (failed_attempts BETWEEN 0 AND 20);
ALTER TABLE telegram_bot_state ADD CONSTRAINT telegram_bot_state_failed_pair_ck CHECK (
    (failed_update_id IS NULL AND failed_attempts = 0)
    OR (failed_update_id IS NOT NULL AND failed_attempts > 0)
);

CREATE TABLE application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE RESTRICT,
    previous_status VARCHAR(40),
    new_status VARCHAR(40) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source VARCHAR(40) NOT NULL,
    CONSTRAINT application_history_previous_status_ck CHECK (
        previous_status IS NULL OR previous_status IN
            ('SAVED', 'APPLIED', 'INTERVIEW', 'REJECTED', 'OFFER', 'WITHDRAWN')
    ),
    CONSTRAINT application_history_new_status_ck CHECK (
        new_status IN ('SAVED', 'APPLIED', 'INTERVIEW', 'REJECTED', 'OFFER', 'WITHDRAWN')
    ),
    CONSTRAINT application_history_source_ck CHECK (
        source IN ('TELEGRAM_COMMAND', 'TELEGRAM_CALLBACK', 'INTERNAL')
    )
);
CREATE INDEX application_status_history_application_idx
    ON application_status_history(application_id, changed_at, id);
