CREATE TABLE llm_budget_control (
    id SMALLINT PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT llm_budget_control_singleton_ck CHECK (id = 1)
);

INSERT INTO llm_budget_control (id, updated_at, version)
VALUES (1, CURRENT_TIMESTAMP, 0);

CREATE TABLE llm_budget_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_key VARCHAR(64) NOT NULL UNIQUE,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    operation_type VARCHAR(60) NOT NULL,
    provider VARCHAR(120) NOT NULL CHECK (TRIM(provider) <> ''),
    model VARCHAR(200) NOT NULL CHECK (TRIM(model) <> ''),
    budget_day DATE NOT NULL,
    budget_month DATE NOT NULL,
    max_input_tokens BIGINT NOT NULL CHECK (max_input_tokens > 0),
    max_output_tokens BIGINT NOT NULL CHECK (max_output_tokens > 0),
    max_attempts INTEGER NOT NULL CHECK (max_attempts BETWEEN 1 AND 4),
    reserved_cost_usd NUMERIC(18,8) NOT NULL CHECK (reserved_cost_usd > 0),
    final_cost_usd NUMERIC(18,8) CHECK (final_cost_usd IS NULL OR final_cost_usd >= 0),
    status VARCHAR(30) NOT NULL,
    provider_started_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reconciled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT llm_budget_reservation_status_ck CHECK (
        status IN ('RESERVED', 'SETTLED', 'RELEASED', 'ABANDONED', 'LATE_SETTLED')
    ),
    CONSTRAINT llm_budget_reservation_month_ck CHECK (
        EXTRACT(DAY FROM budget_month) = 1
    ),
    CONSTRAINT llm_budget_reservation_reconciled_ck CHECK (
        (status = 'RESERVED' AND final_cost_usd IS NULL AND reconciled_at IS NULL)
        OR (status <> 'RESERVED' AND final_cost_usd IS NOT NULL AND reconciled_at IS NOT NULL)
    )
);
CREATE INDEX llm_budget_reservations_day_idx
    ON llm_budget_reservations(budget_day, status);
CREATE INDEX llm_budget_reservations_month_idx
    ON llm_budget_reservations(budget_month, status);
CREATE INDEX llm_budget_reservations_expiry_idx
    ON llm_budget_reservations(status, expires_at);

CREATE TABLE job_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
    candidate_profile_id BIGINT REFERENCES candidate_profiles(id) ON DELETE RESTRICT,
    candidate_profile_version INTEGER,
    operation_type VARCHAR(60) NOT NULL,
    provider VARCHAR(120) NOT NULL CHECK (TRIM(provider) <> ''),
    model VARCHAR(200) NOT NULL CHECK (TRIM(model) <> ''),
    prompt_version VARCHAR(80) NOT NULL CHECK (TRIM(prompt_version) <> ''),
    job_content_hash VARCHAR(64) NOT NULL,
    candidate_truth_hash VARCHAR(64),
    cache_key VARCHAR(64) NOT NULL UNIQUE,
    attempt_count INTEGER NOT NULL DEFAULT 1 CHECK (attempt_count BETWEEN 1 AND 1000),
    reservation_id BIGINT REFERENCES llm_budget_reservations(id) ON DELETE SET NULL,
    role_summary TEXT,
    must_have_requirements TEXT,
    preferred_requirements TEXT,
    responsibilities TEXT,
    experience_requirement TEXT,
    education_requirement TEXT,
    language_requirement TEXT,
    location_constraints TEXT,
    work_authorization_signals TEXT,
    candidate_strengths TEXT,
    candidate_gaps TEXT,
    ambiguous_requirements TEXT,
    evidence_references TEXT,
    confidence_score INTEGER,
    status VARCHAR(30) NOT NULL,
    fallback_used BOOLEAN NOT NULL,
    failure_category VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    retry_after TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT job_analysis_hash_ck CHECK (
        CHAR_LENGTH(job_content_hash) = 64
        AND CHAR_LENGTH(cache_key) = 64
        AND (candidate_truth_hash IS NULL OR CHAR_LENGTH(candidate_truth_hash) = 64)
    ),
    CONSTRAINT job_analysis_candidate_ck CHECK (
        (candidate_profile_id IS NULL AND candidate_profile_version IS NULL AND candidate_truth_hash IS NULL)
        OR (candidate_profile_id IS NOT NULL AND candidate_profile_version > 0
            AND candidate_truth_hash IS NOT NULL)
    ),
    CONSTRAINT job_analysis_status_ck CHECK (
        status IN ('IN_PROGRESS', 'SUCCEEDED', 'FALLBACK')
    ),
    CONSTRAINT job_analysis_confidence_ck CHECK (
        confidence_score IS NULL OR confidence_score BETWEEN 0 AND 100
    ),
    CONSTRAINT job_analysis_completion_ck CHECK (
        (status = 'IN_PROGRESS' AND completed_at IS NULL AND fallback_used = FALSE)
        OR (status = 'SUCCEEDED' AND completed_at IS NOT NULL AND fallback_used = FALSE)
        OR (status = 'FALLBACK' AND completed_at IS NOT NULL AND fallback_used = TRUE
            AND failure_category IS NOT NULL)
    )
);
CREATE INDEX job_analyses_job_idx ON job_analyses(job_id, created_at DESC);
CREATE INDEX job_analyses_profile_idx
    ON job_analyses(candidate_profile_id, candidate_profile_version);

ALTER TABLE llm_usage_events ADD COLUMN reservation_id BIGINT;
ALTER TABLE llm_usage_events ADD COLUMN request_key VARCHAR(64);
ALTER TABLE llm_usage_events ALTER COLUMN estimated_cost_usd TYPE NUMERIC(18,8);
ALTER TABLE llm_usage_events ADD CONSTRAINT llm_usage_reservation_fk
    FOREIGN KEY (reservation_id) REFERENCES llm_budget_reservations(id) ON DELETE SET NULL;
ALTER TABLE llm_usage_events ADD CONSTRAINT llm_usage_request_key_ck
    CHECK (request_key IS NULL OR CHAR_LENGTH(request_key) = 64);
CREATE UNIQUE INDEX llm_usage_events_reservation_unique
    ON llm_usage_events(reservation_id);
CREATE INDEX llm_usage_events_request_key_idx ON llm_usage_events(request_key);
